apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: edc-cors-config-consumer
  namespace: consumer
spec:
  headers:
    accessControlAllowOriginList: 
      - "*"
    accessControlAllowMethods: 
      - "GET" 
      - "POST" 
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowHeaders: 
      - "Authorization"
      - "Content-Type"
      - "Origin"
      - "Cookie"
      - "x-api-key"
    #accessControlAllowCredentials: true
    accessControlMaxAge: 3600